version: "3.3"
services:
    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
            - 8025:8025
            - 8080:8080
        volumes:
            - ./:/var/www/
            - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - orders

    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        expose:
            - 9000:9000
        volumes:
            - .:/var/www
        networks:
            - orders

    mysql:
        image: mariadb
        container_name: mysql
        restart: unless-stopped
        ports:
            - 3306:3306
        volumes: 
            - mysql:/var/lib/mysql
        environment:  
            MYSQL_ROOT_PASSWORD: eUqbk82jUe
            MYSQL_DATABASE: orders
        networks:
            - orders

    mail:
        image: mailhog/mailhog
        container_name: mailhog
        restart: unless-stopped
        ports:
            - 1025:1025
        networks:
            - orders

    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - 6379:6379
        volumes:
            - redis:/root/redis
        environment:
            - REDIS_PASSWORD=uT1bH21Opw
        networks:
            - orders


volumes:
    mysql:
        driver: local
    redis:
        driver: local

networks:
    orders:
        driver: bridge